### PR TITLE
v3

### LINKED ISSUE #3: merge in tests from 25

### PR DESCRIPTION
**Pull request by nathanallen**
closes #3 
see pull request #6 to run these tests against solution

This PR includes:
- refactored / improved tests
- better style guide compliance

@cofauver if you have time to walk through it and note down sticking points, that would be great! In particular, I'm concerned about tests/error messages being clear to students.

### CODE REVIEW

**Comment by cofauver** [comment]
Some initial comments after working through this. 

### 1

It seems like some of the tests don't _force_ the expected or hoped for solution. Example: I can hardcode my endpoint to always return the element with _id of 3 because I figured out that that's the one the test asks for. I get the test passing without building the functionality for returning the specific ID. A pretty quick fix would be to randomize the id number that it asks for.

``` javascript
app.get('/api/todos/:id', function show(req, res) {
  res.json(200, todos[2]);
});
```

### 2

They are going to have a hard time with the size and complexity of the request json. I don't know of a really good way of looking at `req` other than logging it to terminal, where it'll look quite ugly and hard to sift through. 

### 3

The paradigm of coding in order to get the tests to pass is tough in itself and we'll need to scaffold that well.

### 4

Because it's their first shot at building an API, I think filling in the endpoint functionality with comments in the starting code will help them.

Example:

``` javascript
app.get('/api/todos/search', function search(req, res){
  /* When a user hits this endpoint, we want the server to
   * respond with an object with one key value pair. The expected key
   * is todos and the value will be a list of all of the todos
   * that had a task property containing the search query.
   */
});
```

On the other hand, maybe this defeats the purpose of having the tests for them to look at. Maybe a sparser comment would be appropriate.

``` javascript
app.get('/api/todos/search', function search(req, res){
  /* This endpoint responds with the search results from the
   * query in the request.
   */
});
```

At the bottom of this comment I've included possible versions of the "sparse" comments.

### 5

The wording in the test for the search endpoint is confusing:
"should list all todos that contain the search term in their title" 

It contains the search term in the property `task` not in a property called title. Is this better wording? 
"should list all todos that contain the search term in the task property" 

``` javascript
/*
 * JSON API Endpoints
 */

app.get('/api/todos/search', function search(req, res){
  /* This endpoint responds with the search results from the
   * query in the request.
   */
});

app.get('/api/todos', function index(req, res) {
  /* This endpoint responds with all of the todos
   */
});

app.post('/api/todos', function create(req, res) {
  /* This endpoint will add a todo to our "database"
   * and respond with the newly created todo.
   */
});

app.get('/api/todos/:id', function show(req, res) {
  /* This endpoint will return a single todo with the
   * id specified in the route parameter (:id)
   */
});

app.put('/api/todos/:id', function update(req, res) {
  /* This endpoint will update a single todo with the
   * id specified in the route parameter (:id) and respond
   * with the newly updated todo.
   */
});

app.delete('/api/todos/:id', function destroy(req, res) {
  /* This endpoint will delete a single todo with the
   * id specified in the route parameter (:id) and respond
   * with the updated list of todos.
   */
});
```

**Comment by nathanallen** [comment]
Good feedback.
1. Done.
2. Server side logging is pretty gnarly in node, esp. the request object. Unavoidable. They have to start building that skill.
3. Last time I did brief intro to testing/TDD by showing them the first few minutes of https://www.youtube.com/watch?v=983zk0eqYLY and talking them through it.
4. (and 5) I like this idea a lot so long as they don't stop looking at the test output to guide them. Would you like to add this bit? (Note: search route MUST be above show/put/delete routes, but they really must do it last. Perhaps number them in the comments?)
5. Reworded search test, and slightly improved the test. This is a bonus, so I'm less concerned.

**Comment by nathanallen** [comment]
Feel free to merge and fork before Tuesday. I'll try to be in touch.

**Comment by cofauver** [comment]
I actually just looked more carefully at the `app.js` file and it needs some stylistic updates to conform to our style guide. I'm going to make these changes, push to v3 and make another PR. I hope that's not a major hassle.

**Pull request merged**
